### PR TITLE
Otel ctx prop

### PR DESCRIPTION
**Pull request by jdcasey**
Depends on #59.

This adds Opentelemetry support, including support for sending trace data to Honeycomb and propagating trace context to the upstream service. I've tested in the following conditions:

* Tracing disabled (the default state)
* Tracing to local opentelemetry-collector (using `podman run -ti --rm -p 4317:4317 otel/opentelemetry-collector`)
* Tracing to Honeycomb, in conjunction with a local Indy instance (where the gateway was configured to proxy Indy)

### CODE REVIEW

**Comment by ruhan1** [comment]
This looks great. But hard to review :) Maybe merge the prev one and rebase it?

**Comment by jdcasey** [comment]
@ruhan1 @ligangty I've rebased to account for the merge of #59 , and added a bit more logic tightening. I've also added more fields to give details we can use to filter traces for different branches in the logic, along with things that might fail silently or indicate poor upstream reliability.

**Review by ruhan1 — APPROVED** [review]
Look great!

**Comment by jdcasey** [comment]
I'm really not sure why CI keeps failing

**Pull request merged**
